### ISSUE TITLE
ERROR while compiling core.v0.15~preview.125.10+20 | macos/x86_64

### ISSUE THREAD

**Issue by denis631** [janestreet/core#148] opened 2021-10-29 15:09 UTC
I am experiencing issues installing the latest core.
Console output:
```
#=== ERROR while compiling core.v0.15~preview.125.10+20 =======================#
# context     2.1.0 | macos/x86_64 | ocaml-base-compiler.4.11.1 | https://ocaml.janestreet.com/opam-repository
# path        ~/Documents/mongo_utils/_opam/.opam-switch/build/core.v0.15~preview.125.10+20
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p core -j 11
# exit-code   1
# env-file    ~/.opam/log/core-47318-d2765e.env
# output-file ~/.opam/log/core-47318-d2765e.out
### output ###
# [...]
# /Library/Developer/CommandLineTools/usr/bin/ranlib: file: bigstring_unix/src/libbigstring_unix_stubs.a(recvmmsg.o) has no symbols
# /Library/Developer/CommandLineTools/usr/bin/ranlib: file: bigstring_unix/src/libbigstring_unix_stubs.a(recvmmsg.o) has no symbols
#           cc core_unix/src/core_unix_time_stubs.o (exit 1)
# (cd _build/default/core_unix/src && /usr/local/opt/ccache/libexec/cc -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT -O2 -fno-strict-aliasing -fwrapv -D_LARGEFILE64_SOURCE -g -I /Users/denis.grebennicov/Documents/folder/_opam/lib/ocaml -I /Users/denis.grebennicov/Documents/folder/_opam/lib/base -I /Users/denis.grebennicov/Documents/folder/_opam/lib/base/bas[...]
# core_unix_time_stubs.c:57:13: error: implicit declaration of function 'clock_getcpuclockid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
#   int ret = clock_getcpuclockid(pid, &clock);
#             ^
# core_unix_time_stubs.c:57:13: note: did you mean 'caml_clock_getcpuclockid'?
# core_unix_time_stubs.c:52:16: note: 'caml_clock_getcpuclockid' declared here
# CAMLprim value caml_clock_getcpuclockid(value v_pid) {
#                ^
# 1 error generated.
```

**Comment by bcc32** [comment] 2021-10-29 18:03
Thanks for reporting this.  It seems likely that this is a duplicate of #144.

**Comment by bcc32** [comment] 2022-06-25 20:56
Closing as a duplicate of #144.  Please reopen if that's not accurate.

**Closed by bcc32** 2022-06-25 20:56 UTC
Labels: forwarded-to-js-devs
