### ISSUE TITLE
ocamlbuild(0.14) -> core(v0.12.0) -> fails at runtime

### ISSUE THREAD

**Issue by pat227** [janestreet/core#125] opened 2019-03-13 02:30 UTC
The inclusion of the latest version of Core in any project that uses the latest version of ocamlbuild can compile but consistently throws an error at runtime, regardless of input. This is on a Devuan box, but I could also try this  on a Debian box.

I started a simple project from scratch and with just 2 modules, and one of them merely being dedicated to command line parsing, I could not get the program to work with the most recent versions of OCaml (4.07.1), Core (v.0.12.0), and ocamlbuild (0.14) available through opam (v2.0.0). The project compiles but at runtime I get this error:

Fatal error: cannot load shared library dllcore_stubs
Reason: /<home_path>/.opam/4.07.1/lib/stublibs/dllcore_stubs.so: undefined symbol: caml_exn_Invalid_argument

I double checked my environment variables. And this was not within an emacs shell. In my Makefile I was passing -pkgs to ocamlbuild a list including core and not much else, and I experimented with adding base and core_kernel, but that didn't help. I slowly stripped away code and dependencies of anything related to Core, but the error persisted until I completely removed Core. I was not even using Core for command line parsing. Compilation was always successful, however.  Once Core was gone, I got no more runtime errors.

Finally, I gave up and downgraded to Ocaml 4.06.0 and Core 0.11.3 and the same project compiles and runs just fine while including Core. Considering that my version of ocamlbuild did not downgrade, I suspect something changed over at Core. Has anyone else seen this issue?

I have also since written dune files to compile the same code base using dune. Compilation is successful and the program executes without error. I'm not married to ocamlbuild but it would be nice to be able to compile projects that include Core with ocamlbuild. 

I wrote to the maintainers of ocamlbuild and they directed me here. I fear the worst and that this will never get fixed by either side...please let's not go there.

Thank you.

**Comment by diml** [comment] 2019-03-13 10:48
The next step is to determine whether the problem comes from Core or ocamlbuild. What happens if downgrade only of them?

**Comment by pat227** [comment] 2019-03-13 11:51
Please see my original message. Downgrading only Core solves the problem. I
will try downgrading ocamlbuild shortly and report back.

**Comment by diml** [comment] 2019-03-13 12:17
Hmm, I now remember fixing something like this. I believe the problem is native vs bytecode, i.e. `caml_exn_Invalid_argument` is only available in native mode. I guess you are building in bytecode with ocamlbuild and in native with dune?

In any case, this is fixed in master. I guess we will need to do a minor release with the fix.

**Comment by pat227** [comment] 2019-03-14 02:09
Excellent to hear that.

Yes, I was building bytecode with ocamlbuild and native with dune. Dune is
new to me and I have yet to read up how to specify building bytecode; I
hadn't even realized that discrepancy yet.

Changing my ocamlbuild (latest version 0.14) to compile native instead of
bytecode, in combination with the latest versions of Ocaml (4.07.1) and
Core (v0.12.0), also solves the problem. I get an executable with no fatal
runtime error.

Downgrading Core to v0.11.3 also solves the problem for bytecode
compilation using ocamlbuild.

**Comment by omeid** [comment] 2019-03-14 06:59
I have the same problem with using `Core` in `utop`.

```
$ utop -version
The universal toplevel for OCaml, version 2.3.0, compiled for OCaml version 4.07.1

 $ ocamlbuild --version
ocamlbuild 0.14.0

 $ dune --version
1.8.2

$ ocaml --version
The OCaml toplevel, version 4.07.1
`

I have installed both Core and utop with opam (2.0.3).

**Comment by omeid** [comment] 2019-03-14 07:00
Actually, the same problem in ocaml toplevel too, so you can ignore utop.

**Comment by diml** [comment] 2019-03-14 08:12
Yh, that's expected as the toplevel is running in bytecode

**Comment by gabefighter99** [comment] 2019-03-18 11:50
Do let us know when! Thank-you for the quick replies, that was extremely helpful!

**Comment by diml** [comment] 2019-03-18 12:02
I submitted the release this morning: https://github.com/ocaml/opam-repository/pull/13687

**Closed** 2019-03-19 11:01 UTC
