### ISSUE TITLE
Core_top is missing a pretty printer

### ISSUE THREAD

**Issue by mmottl** [janestreet/core#60] opened 2015-07-05 21:11 UTC
The current Core release (112.35.00) reports the following error in the toplevel when "core" is required:

```
/Users/mmottl/.opam/4.02.2/lib/core/core_top.cma: loaded
Unbound value String_id.pp.
```

**Comment by genkimarshall** [comment] 2015-08-13 06:01
It's so hacky, I'm almost embarrassed to suggest this, but it's relevant at least.
I doubt it will lead to the solution, but here goes:

I wanted to keep:
```ocaml
#require "core.syntax"
#require "core.top"
open Core.Std
```
in my `.ocamlinit`.

But, I was faced with two `Unbound value String_id.pp` every time I opened `utop`.
I found things would all seem to work fine by the end, e.g. `String_id.pp` seemed to be correctly bound after.

So, I found that replacing this with
```ocaml
#require "core.syntax"
open Core.Std
#require "core.top" (* Replace with "core" as it seems OP wanted. *)
```
led to no errors being shown, and no unexpected behavior afterwards.

My _very_ uneducated guess is that something in the requiring of `core.top` expects a certain order to how things are being loaded in..? And so pulling in the `Core.Std` namespace allows it to think `String_id` has correctly loaded even though only it's name has been registered?
I'm certain this analysis betrays my lack of knowledge with how this all works, but it seems to work as a temporary hack for me. Please let me know if I'm missing something.

**Comment by diml** [comment] 2015-08-13 09:41
The pretty-printer was registered under the wrong name. This was fixed internally and so will be part of the next release.

**Comment by genkimarshall** [comment] 2015-08-13 13:54
Alright, thanks for the update.

**Comment by agarwal** [comment] 2015-10-03 11:46
Can close this issue since it appears to be fixed in the latest Core.

**Closed** 2015-10-05 02:34 UTC
Labels: bug
